import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

export class OAuthGoogleDto {
  @ApiProperty({
    example: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjkifQ.google-id-token',
    description: 'Google ID token from the client SDK (not a server client-secret)',
  })
  @IsString()
  idToken!: string;

  @ApiPropertyOptional({
    description: 'Nonce generated by the client for the OpenID request, verified when present',
  })
  @IsOptional()
  @IsString()
  nonce?: string;
}
