import { SocialMode, SocialQuestion } from './social.types';

// Original seed IDs are stable. All content remains draft pending human editorial review.
const seed: [SocialMode, string, string, string][] = [
  ['light','Q001','changed-habit','إيه حاجة كنت بتتريق عليها… وبقيت بتعملها؟'],
  ['light','Q002','defend-food','إيه أكلة مستعد تدافع عنها لو القعدة كلها ضدك؟'],
  ['light','Q003','personal-manual','لو صحابك عملوا لك دليل استخدام، أول تحذير فيه هيبقى إيه؟'],
  ['light','Q004','unused-purchase','إيه حاجة اشتريتها بحماس… وبعدين نسيت إنها عندك؟'],
  ['light','Q005','catchphrase','إيه جملة بتقولها كتير لدرجة إن صحابك حفظوها؟'],
  ['light','Q006','day-film','لو يومك النهارده عنوان فيلم، هتسميه إيه؟'],
  ['light','Q007','overprepared','إيه حاجة بتاخد منك استعداد أكبر بكتير من حجمها؟'],
  ['light','Q008','silly-contest','لو اتفتحت مسابقة في حاجة ملهاش لازمة، تحب تنافس في إيه؟'],
  ['light','Q009','mispronounced-word','إيه كلمة فضلت تنطقها غلط لحد ما حد خد باله؟'],
  ['light','Q010','signature-sandwich','لو هتعمل ساندوتش باسمك، هتحط فيه إيه؟'],
  ['light','Q011','hiding-in-sight','إيه حاجة بتضيع منك… وتطلع قدام عينك؟'],
  ['light','Q012','accidental-late-night','إيه أغرب سبب خلاك تسهر وإنت ناوي تنام بدري؟'],
  ['light','Q013','secret-mission','إيه حاجة بسيطة بتعملها كأنها مهمة سرية؟'],
  ['light','Q014','phone-complaint','لو موبايلك اشتكى منك شكوى واحدة، هيقول إيه؟'],
  ['light','Q015','serious-game','إيه لعبة بتاخدها بجد زيادة عن اللزوم؟'],
  ['light','Q016','five-minutes','إيه حاجة بتقول هتخلصها في خمس دقايق… ومبتخلصش؟'],
  ['light','Q017','cancel-errand','لو تقدر تلغي مشوار واحد بيتكرر في حياتك، هتلغي إيه؟'],
  ['light','Q018','small-talent','إيه موهبة صغيرة عندك محدش بيديها حقها؟'],
  ['light','Q019','tiny-joy','إيه حاجة بتفرحك وإنت عارف إنها تافهة شوية؟'],
  ['light','Q020','imaginary-shop','لو عندك محل ومش مهم يكسب، هيبيع إيه؟'],
  ['stories','Q021','lost-route','احكي عن مرة قلت أنا عارف الطريق… وطلعت تايه.'],
  ['stories','Q022','household-custom','إيه حاجة كنت فاكر إن كل البيوت بتعملها… وطلعت عندكم بس؟'],
  ['stories','Q023','repair-gone-wrong','احكي عن مرة حاولت تصلّح الدنيا… لخبطتها أكتر.'],
  ['stories','Q024','unplanned-outing','إيه أحلى موقف حصل في خروجة مكانتش مترتبة؟'],
  ['stories','Q025','forgotten-name','احكي عن مرة نسيت اسم حد… وتصرفت إزاي؟'],
  ['stories','Q026','embarrassment-later','إيه موقف محرج بقى دلوقتي حكاية بتضحكك؟'],
  ['stories','Q027','younger-teacher','احكي عن مرة اتعلمت حاجة من شخص أصغر منك.'],
  ['stories','Q028','ordinary-coincidence','إيه أجمل صدفة حصلت لك في مكان عادي؟'],
  ['stories','Q029','kitchen-surprise','احكي عن مرة دخلت المطبخ تعمل حاجة… طلعت حاجة تانية.'],
  ['stories','Q030','small-world','إيه موقف خلاك تقول الدنيا صغيرة فعلًا؟'],
  ['stories','Q031','unexpected-good-day','احكي عن مرة توقعت يوم ممل… وطلع يوم حلو.'],
  ['stories','Q032','returned-object','إيه حاجة ضاعت منك ورجعت لك بطريقة غريبة؟'],
  ['stories','Q033','stranger-help','احكي عن مرة ساعدك حد من غير ما يعرفك.'],
  ['stories','Q034','school-memory','إيه موقف من المدرسة لسه فاكره بتفاصيله؟'],
  ['stories','Q035','first-try-repeat','احكي عن أول مرة جرّبت حاجة وقلت لازم أعملها تاني.'],
  ['stories','Q036','company-shortens-route','إيه أطول مشوار حسّيته قصير عشان الصحبة؟'],
  ['stories','Q037','misread-instructions','احكي عن مرة فهمت تعليمات غلط… وإيه اللي حصل؟'],
  ['stories','Q038','handmade-pride','إيه حاجة عملتها بإيدك واتبسطت بيها حتى لو مش مظبوطة؟'],
  ['stories','Q039','weather-new-plan','احكي عن مرة الجو غيّر خطتك… وطلع التغيير أحسن.'],
  ['stories','Q040','simple-gift','إيه هدية بسيطة لسه فاكر حكايتها؟'],
  ['closer','Q041','first-impression','إيه حاجة الناس بتفهمها عنك غلط أول ما تعرفك؟'],
  ['closer','Q042','new-place-comfort','إيه تفصيلة صغيرة بتخليك ترتاح في مكان جديد؟'],
  ['closer','Q043','heavy-day-support','لما يومك يبقى تقيل، بتحب اللي قدامك يعمل إيه؟'],
  ['closer','Q044','changed-opinion','إيه رأي اتغيّر عندك لما جرّبت بنفسك؟'],
  ['closer','Q045','valued-trait','إيه حاجة بتحبها في طريقتك ومش حابب تغيّرها؟'],
  ['closer','Q046','learn-at-ease','لو عندك وقت تتعلم حاجة على مهلك، هتختار إيه؟'],
  ['closer','Q047','feeling-valued','إيه تصرف بسيط بيحسسك إن اللي قدامك مقدّرك؟'],
  ['closer','Q048','helpful-habit','إيه عادة صغيرة عملت فرق حلو في يومك؟'],
  ['closer','Q049','good-outing','إيه معنى الخروجة الحلوة بالنسبة لك؟'],
  ['closer','Q050','friendship-signal','بتعرف إنك بقيت صاحب حد من أنهي موقف؟'],
  ['closer','Q051','alone-enjoyment','إيه حاجة بتحب تعملها لوحدك عشان تستمتع بيها؟'],
  ['closer','Q052','gentler-judgment','إيه تجربة خلتك تبقى أهدى في حكمك على الناس؟'],
  ['closer','Q053','patience','إيه حاجة كنت مستعجل عليها وبقيت بتديها وقتها؟'],
  ['closer','Q054','extra-hour','لو يومك فيه ساعة زيادة، تحب تسيبها لإيه؟'],
  ['closer','Q055','useful-advice','إيه نصيحة بسيطة جرّبتها وطلعت نافعة؟'],
  ['closer','Q056','favorite-topic','إيه حاجة بتحب الناس تسألك عنها؟'],
  ['closer','Q057','keep-going','لما تبدأ حاجة جديدة، إيه اللي بيشجعك تكمّل؟'],
  ['closer','Q058','old-place-detail','إيه تفصيلة في مكان قديم نفسك ترجع تشوفها؟'],
  ['closer','Q059','saying-no','إيه حاجة بقيت بتقول لها لأ عشان تريح يومك؟'],
  ['closer','Q060','self-thanks','لو هتشكر نفسك على حاجة عملتها مؤخرًا، هتكون إيه؟'],
];
const additions: Record<SocialMode, [string, string][]> = {
  light: [
    ['remote-control','لو الريموت عنده زرار مخصوص لك، هيعمل إيه؟'],
    ['ridiculous-rule','لو هتضيف قانون مضحك للقعدة، هيبقى إيه؟'],
    ['queue-commentary','لو فيه معلّق على وقفتك في الطابور، هيقول إيه؟'],
    ['wrong-soundtrack','إيه أغنية لو اشتغلت وإنت داخل أوضة هتبوّظ هيبتك؟'],
    ['invented-word','لو هتخترع كلمة لحالة بتحصل لك كتير، هتكون إيه؟'],
    ['talking-furniture','لو كرسيك بيتكلم، إيه أول سؤال هيسأله لك؟'],
    ['restaurant-menu-name','إيه أكلة اسمها أفخم بكتير من شكلها في رأيك؟'],
    ['pointless-superpower','لو عندك قوة خارقة تنفع في حاجة صغيرة بس، تختار إيه؟'],
    ['silly-museum','لو عملنا متحف للحاجات اللي في جيبك، أغرب معروض هيبقى إيه؟'],
    ['unexpected-ringtone','إيه صوت مينفعش أبدًا يبقى نغمة موبايل؟'],
    ['object-rebrand','لو هتغيّر اسم المكنسة لاسم فخم، هتسميها إيه؟'],
    ['autocorrect','إيه كلمة الكيبورد بيصر يصلّحها وإنت مش طالب منه؟'],
    ['greeting-style','لو كل حد له تحية دخول مخصوصة، تحيتك شكلها إيه؟'],
    ['shelf-arrangement','إيه حاجة بترتبها على مزاجك حتى لو محدش فاهم النظام؟'],
    ['instant-judge','إيه حاجة تعرف تحكم عليها من أول لقمة أو نظرة؟'],
    ['fictional-job','لو فيه وظيفة لحارس الغفوة، تتخيل يومه عامل إزاي؟'],
    ['tea-debate','إيه تفصيلة في كوباية الشاي ممكن تفتح جدال عندكم؟'],
    ['silent-challenge','لو قعدنا دقيقة من غير كلام، إيه أكتر حاجة هتضحكك؟'],
    ['fake-advert','لو هتعمل إعلان لكيس فاضي، هتقول عليه إيه؟'],
    ['sock-mystery','لو فردة الشراب التانية سابت جواب، تتوقع مكتوب فيه إيه؟'],
    ['awkward-smalltalk','إيه سؤال عادي بيخليك تنسى الكلام أول ما يتقال؟'],
    ['replay-expression','إيه تعبير وشك بيعمله قبل ما تلحق تتكلم؟'],
    ['food-shape','لو الأكل كله لازم يبقى شكل واحد، هتختار أنهي شكل؟'],
    ['household-commentator','إيه جهاز في البيت محتاج حد يشرح له شغله؟'],
    ['weird-app','لو هتعمل تطبيق بيحل مشكلة مضحكة، مشكلته إيه؟'],
    ['fake-award','إيه جايزة هزلية نفسك تتعمل عشان ناس كتير تستحقها؟'],
    ['walking-speed','إيه اللي بيخليك تمشي بسرعة كأنك في سباق؟'],
    ['overdramatic-reaction','إيه حاجة صغيرة بتقول عليها يا نهار أبيض؟'],
    ['wrong-tool','إيه أداة بتستخدمها في شغلانة غير اللي اتعملت لها؟'],
    ['imaginary-sponsor','لو يومك له راعي رسمي من حاجات البيت، هيبقى إيه؟'],
    ['emoji-mismatch','إيه رمز في الرسائل معناه عندك غير معناه عند صحابك؟'],
    ['background-extra','لو ظهرت كومبارس في فيلم، تحب تبقى بتعمل إيه؟'],
    ['odd-collection','لو هتجمع حاجة غريبة من غير تكلفة، هتجمع إيه؟'],
    ['sound-imitation','إيه صوت بتحب تقلّده حتى لو التقليد مش قريب؟'],
    ['phone-gallery-title','لو صور موبايلك معرض، اسم المعرض هيكون إيه؟'],
    ['seasoning-policy','إيه حاجة بتحط عليها بهارات والناس بتستغرب؟'],
    ['daily-plot-twist','إيه تفصيلة لو اتغيّرت الصبح تعتبرها مفاجأة كبيرة؟'],
    ['absurd-sign','لو تكتب لافتة على باب التلاجة، هتكتب إيه؟'],
    ['inanimate-friend','لو هتختار حاجة من أوضتك تبقى صاحبك، تختار إيه؟'],
    ['rewind-button','إيه لحظة بسيطة بتحب تعيدها كأن فيها زرار إعادة؟'],
  ],
  stories: [
    ['wrong-recipient','احكي عن رسالة بعتها للشخص الغلط واتداركتها إزاي.'],
    ['public-transport','إيه موقف في مواصلات فضلت تحكيه بعد ما وصلت؟'],
    ['power-cut','احكي عن مرة النور قطع وطلعت منها بذكرى لطيفة.'],
    ['borrowing','احكي عن حاجة استعرتها ورجّعتها ومعاها حكاية.'],
    ['unexpected-team','إيه مرة اشتغلت مع ناس متعرفهمش واتفقتوا بسرعة؟'],
    ['mistranslation','احكي عن كلمة فهمتها بمعنى مختلف واتضح المقصود بعدين.'],
    ['lost-ticket','إيه موقف حصل لك وإنت بتدور على تذكرة أو ورقة مهمة؟'],
    ['rain-shelter','احكي عن مرة استنيت في مكان غريب عشان المطر.'],
    ['neighbor-moment','إيه موقف بسيط مع جار فضلت فاكره؟'],
    ['last-minute-save','احكي عن مرة لحقت حاجة في آخر لحظة.'],
    ['surprise-visitor','إيه زيارة مفاجئة غيّرت شكل اليوم؟'],
    ['old-photo','احكي عن صورة قديمة لقيتها وافتكرت اللي وراها.'],
    ['new-recipe','إيه مرة جرّبت وصفة من غير كل المكونات وعملت إيه؟'],
    ['patient-practice','احكي عن حاجة فضلت تجرّبها لحد ما ظبطت معاك.'],
    ['missed-stop','احكي عن مرة عدّيت المكان اللي كنت رايحه من غير ما تاخد بالك.'],
    ['wrong-date','إيه موقف حصل بسبب لخبطة في يوم أو معاد؟'],
    ['unexpected-applause','احكي عن مرة الناس شجعتك وإنت مكنتش متوقع.'],
    ['old-friend-contact','إيه حكاية رجوع كلام مع صاحب قديم بعد غياب؟'],
    ['kind-correction','احكي عن مرة حد صحّح لك حاجة بطريقة مريحة.'],
    ['broken-zip','إيه موقف اتصرفت فيه بحل سريع لمشكلة في لبس أو شنطة؟'],
    ['shared-wait','احكي عن كلام بدأ وإنت مستني دورك وانتهى بصحوبية.'],
    ['object-discovery','إيه حاجة لقيتها وإنت بترتب ومكنتش عارف إنها لسه موجودة؟'],
    ['homemade-game','احكي عن لعبة اخترعتوها وإنتوا زهقانين.'],
    ['helped-explain','إيه مرة شرحت حاجة لحد وفهمتها إنت أحسن؟'],
    ['unexpected-responsibility','احكي عن مرة مسكت مسؤولية صغيرة فجأة واتصرفت.'],
    ['phone-battery','إيه حكاية يوم موبايلك فصل شحن في وقت مش مناسب؟'],
    ['wrong-size','احكي عن مرة المقاس أو العدد طلع غير اللي حسبته.'],
    ['shared-lunch','إيه مرة الأكل القليل كفّى ناس أكتر مما توقعت؟'],
    ['unlikely-winner','احكي عن مرة كسبت في حاجة وإنت داخل على قدك.'],
    ['new-nickname','إيه حكاية لقب لطيف اتقال لك ولزق؟'],
    ['behind-scenes','احكي عن مرة شفت التحضير لحاجة بدل النتيجة بس.'],
    ['found-skill','إيه مرة اكتشفت إنك تعرف تعمل حاجة بالصدفة؟'],
    ['reading-aloud','احكي عن مرة قريت حاجة بصوت عالي والناس فهمتها بشكل تاني.'],
    ['unexpected-detour','إيه مكان دخلته تستنى خمس دقايق وقعدت فيه أكتر؟'],
    ['little-tradition','احكي عن عادة بدأت بهزار وبقت بتتكرر في القعدة.'],
    ['planning-role','إيه مرة كنت إنت اللي بترتب للناس وطلع موقف مش متوقع؟'],
    ['saved-notes','احكي عن ورقة كتبتها لنفسك ونفعتك بعد وقت.'],
    ['public-service','إيه موقف لطيف شفته من حد وهو بيعمل شغله؟'],
    ['celebration-mishap','احكي عن احتفال بسيط حصلت فيه لخبطة ظريفة.'],
    ['different-perspectives','إيه موقف حكيتوه إنت وصاحبك وكل واحد فاكره بشكل مختلف؟'],
  ],
  closer: [
    ['conversation-space','إيه اللي بيخلي الكلام مع حد يمشي من غير مجهود؟'],
    ['change-pace','إمتى بتحس إنك محتاج تهدي سرعة يومك؟'],
    ['finishing-signal','إيه علامة صغيرة بتقول لك إنك خلّصت شغل كفاية النهارده؟'],
    ['home-feeling','إيه حاجة بتديك إحساس البيت حتى وإنت في مكان مختلف؟'],
    ['fair-play','إيه معنى اللعب بروح حلوة بالنسبة لك؟'],
    ['asking-help','إيه اللي بيخلي طلب المساعدة أسهل عليك؟'],
    ['respectful-disagreement','إيه طريقة اختلاف بتحس فيها إن رأيك لسه متقدّر؟'],
    ['rest-definition','الراحة عندك أقرب للهدوء ولا للحركة، وليه؟'],
    ['attention-detail','إيه تفصيلة بتحب تاخد بالك منها والناس بتفوتها؟'],
    ['good-listener','إيه علامة بتقول لك إن اللي قدامك بيسمعك فعلًا؟'],
    ['effort-recognition','إيه مجهود صغير بتحب الناس تلاحظه؟'],
    ['simple-boundary','إيه اتفاق بسيط بتحبه قبل ما تبدأ شغل مع حد؟'],
    ['curiosity','إيه موضوع بيخليك تسأل أسئلة كتير من غير ما تحس؟'],
    ['quiet-confidence','إمتى بتكون واثق في قرارك حتى لو مش بتتكلم كتير؟'],
    ['kind-feedback','إيه شكل الملاحظة اللي بتقدر تستفيد منها بسهولة؟'],
    ['shared-routine','إيه روتين بسيط بتحب تشارك فيه حد؟'],
    ['new-beginning','إيه حاجة بتحب تعملها أول يوم في مرحلة جديدة؟'],
    ['encouragement-language','إيه جملة تشجيع بتحس إنها على مقاسك؟'],
    ['creative-energy','إيه جو بيخليك تطلع أفكار أحسن؟'],
    ['decision-style','لما يكون قدامك اختيارين حلوين، بتقرر إزاي؟'],
    ['keeping-promise','إيه وعد صغير لنفسك بتحب تحافظ عليه؟'],
    ['generosity-style','إيه طريقة بسيطة بتحب تفرّح بيها حد؟'],
    ['comfort-food-memory','إيه أكلة مرتبطة عندك بإحساس مريح، مش بطعمها بس؟'],
    ['thoughtful-question','إيه سؤال اتسألته وخلاك تفكر بطريقة جديدة؟'],
    ['group-role','في الشغل الجماعي، إيه دور بتحس إنه مناسب لك؟'],
    ['silence-comfort','إيه اللي بيخلي السكوت مع حد مريح؟'],
    ['daily-priority','إيه حاجة لو أخدت حقها في اليوم بتحس الباقي أسهل؟'],
    ['learning-format','بتستوعب حاجة جديدة أحسن لما تشوفها ولا تجرّبها، وليه؟'],
    ['personal-definition-success','إيه نجاح صغير ممكن محدش يشوفه بس يهمك؟'],
    ['trust-detail','إيه تصرف بيزود ثقتك في حد مع الوقت؟'],
    ['hosting-comfort','لو بتستقبل ناس، إيه أهم حاجة عندك عشان يرتاحوا؟'],
    ['pleasant-surprise','إيه نوع المفاجآت اللي بتحبه حتى لو بسيط؟'],
    ['healthy-competition','إيه اللي بيخلي المنافسة ممتعة لك حتى لو مكسبتش؟'],
    ['time-together','إيه نشاط بتحس إن وقتك مع الناس فيه أحسن؟'],
    ['small-courage','إيه خطوة صغيرة بتحتاج منك شجاعة رغم إنها عادية لغيرك؟'],
    ['creative-expression','إيه طريقة بتحب تعبّر بيها عن فكرة غير الكلام؟'],
    ['welcoming-newcomer','إيه حاجة بتعملها عشان حد جديد يحس إنه وسطنا؟'],
    ['save-memory','إيه ذكرى يومية عادية تحب تفضل فاكرها؟'],
    ['fairness-detail','إيه تفصيلة في التعامل بتحس إنها بتخلي الأمور أعدل؟'],
    ['hopeful-tomorrow','إيه حاجة بسيطة بتخليك متحمس لبكرة؟'],
  ],
};

const THEMES: Record<string, string[]> = {
  food: ['defend-food','signature-sandwich','kitchen-surprise','restaurant-menu-name','tea-debate','food-shape','seasoning-policy','new-recipe','shared-lunch','comfort-food-memory'],
  language: ['catchphrase','mispronounced-word','invented-word','autocorrect','emoji-mismatch','mistranslation','reading-aloud','thoughtful-question'],
  learning: ['small-talent','younger-teacher','first-try-repeat','misread-instructions','handmade-pride','learn-at-ease','helpful-habit','useful-advice','patient-practice','kind-correction','helped-explain','found-skill','learning-format'],
  journeys: ['cancel-errand','lost-route','unplanned-outing','company-shortens-route','weather-new-plan','public-transport','rain-shelter','missed-stop','unexpected-detour'],
  people: ['personal-manual','forgotten-name','stranger-help','small-world','heavy-day-support','feeling-valued','friendship-signal','gentler-judgment','unexpected-team','neighbor-moment','surprise-visitor','old-friend-contact','shared-wait','conversation-space','good-listener','shared-routine','group-role','trust-detail','hosting-comfort','welcoming-newcomer','time-together'],
  memories: ['ordinary-coincidence','school-memory','simple-gift','old-place-detail','old-photo','object-discovery','save-memory','different-perspectives'],
  imagination: ['day-film','silly-contest','phone-complaint','imaginary-shop','remote-control','ridiculous-rule','queue-commentary','talking-furniture','pointless-superpower','silly-museum','unexpected-ringtone','object-rebrand','greeting-style','fictional-job','fake-advert','sock-mystery','weird-app','fake-award','imaginary-sponsor','background-extra','absurd-sign','inanimate-friend','creative-expression'],
  wellbeing: ['new-place-comfort','patience','saying-no','change-pace','finishing-signal','home-feeling','rest-definition','silence-comfort','daily-priority','hopeful-tomorrow'],
  values: ['changed-opinion','valued-trait','self-thanks','fair-play','asking-help','respectful-disagreement','effort-recognition','simple-boundary','quiet-confidence','kind-feedback','decision-style','keeping-promise','generosity-style','personal-definition-success','healthy-competition','small-courage','fairness-detail'],
};
const FAMILY_ALIASES: Record<string,string> = { 'found-skill':'small-talent' };
export const SOCIAL_QUESTIONS: SocialQuestion[] = [
  ...seed.map(([mode, id, familyId, text]) => ({ mode, id, familyId, text })),
  ...(['light', 'stories', 'closer'] as const).flatMap((mode, index) => additions[mode].map(([familyId, text], i) =>
    ({ mode, id: `Q${String(61 + index * 40 + i).padStart(3, '0')}`, familyId, text }))),
].map(q => ({ ...q, familyId:FAMILY_ALIASES[q.familyId] ?? q.familyId, version: 1,
  tags: [Object.entries(THEMES).find(([,families]) => families.includes(q.familyId))?.[0] ?? 'everyday'],
  locale: 'ar-EG', status: 'draft', reviewedAt: null }));
