import {
  BALL_EVENT_BAR,
  BALL_EVENT_GOAL,
  BALL_EVENT_WALL,
  BALL_RADIUS,
  BALL_WALL_RADIUS,
  GOAL_HALF_WIDTH,
  GOAL_HEIGHT,
  GOAL_LINE_Z,
  ballResting,
  createBall,
  kickBall,
  resetBall,
  stepBall,
  type BallPlayer,
  type BallState,
} from './ball-sim';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

type Vec = {
  x: number;
  y: number;
  z: number;
  vx: number;
  vy: number;
  vz: number;
};
type Scenario = {
  name: string;
  start: Vec;
  reset: boolean;
  kick: { dirX: number; dirZ: number; power: number } | null;
  players: BallPlayer[];
  movePlayers: boolean;
  jump?: { step: number; dx: number; dz: number } | null;
  steps: number;
  frames: Array<{ step: number; events: number; toucher: number; state: Vec }>;
  summary: { events: number; goalStep: number; resting: boolean; final: Vec };
};

/** Generated by the frontend's tools/generate-ball-fixture.mjs; byte-identical copy. */
const fixture = JSON.parse(
  readFileSync(join(__dirname, 'ball-sim.fixture.json'), 'utf8'),
) as { dt: number; scenarios: Scenario[] };

const KEYS = ['x', 'y', 'z', 'vx', 'vy', 'vz'] as const;
/** The fixture stores 12 significant digits: anything beyond is drift. */
const EPS = 1e-9;

/** Seeded PRNG so the fuzz run is reproducible. */
function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

describe('ball-sim', () => {
  describe('parity fixture (the same file is asserted by the frontend suite)', () => {
    const scenarios = fixture.scenarios;

    it('covers every case the spec names', () => {
      const names = scenarios.map((s) => s.name).join(' | ');
      for (const needle of [
        'rolling to rest',
        'wall bounce',
        'post hit',
        'crossbar',
        'chip arc',
        'goal inside the posts',
        'wide of the post',
        'over the bar',
        'dribble',
        'keeper',
        'pushed over the line',
        'side net',
      ])
        expect(names).toContain(needle);
    });

    it.each(scenarios.map((s) => [s.name, s] as const))(
      'replays "%s" step for step',
      (_name, s) => {
        const b: BallState = { ...s.start };
        const players = s.players.map((p) => ({ ...p }));
        if (s.reset) resetBall(b);
        if (s.kick) kickBall(b, s.kick.dirX, s.kick.dirZ, s.kick.power);
        const info = { toucher: -1 };
        const dt = fixture.dt;
        const drift: string[] = [];
        let events = 0;
        let goalStep = -1;
        for (const f of s.frames) {
          if (s.jump && f.step === s.jump.step)
            for (const p of players) {
              p.x += s.jump.dx;
              p.z += s.jump.dz;
            }
          const e = stepBall(b, players, players.length, dt, info);
          if (s.movePlayers)
            for (const p of players) {
              p.x += p.vx * dt;
              p.z += p.vz * dt;
            }
          events |= e;
          if (e & BALL_EVENT_GOAL && goalStep < 0) goalStep = f.step;
          if (e !== f.events) drift.push(`step ${f.step}: events ${e}`);
          if (info.toucher !== f.toucher)
            drift.push(`step ${f.step}: toucher ${info.toucher}`);
          for (const k of KEYS)
            if (Math.abs(b[k] - f.state[k]) > EPS)
              drift.push(`step ${f.step}: ${k} ${b[k]} ≠ ${f.state[k]}`);
        }
        expect(drift).toEqual([]);
        expect(events).toBe(s.summary.events);
        expect(goalStep).toBe(s.summary.goalStep);
        expect(ballResting(b)).toBe(s.summary.resting);
      },
    );

    it('scores inside the posts, never wide or over the bar', () => {
      const by = (n: string) => scenarios.find((s) => s.name.includes(n))!;
      expect(by('goal inside the posts').summary.goalStep).toBeGreaterThan(0);
      expect(by('wide of the post').summary.goalStep).toBe(-1);
      expect(by('over the bar').summary.goalStep).toBe(-1);
      expect(by('over the bar').summary.resting).toBe(true);
    });
  });

  it('never leaves the floor or sticks in the goal (seeded fuzz, 2000 kicks)', () => {
    const rand = rng(0x5eed);
    const dt = 1 / 30;
    const players: BallPlayer[] = [];
    const bad: string[] = [];
    for (let run = 0; run < 2000; run++) {
      const b = createBall();
      // Start anywhere on the floor except inside the goal frame (a ball can
      // only get in there by crossing the line, which is a goal).
      do {
        const a = rand() * Math.PI * 2;
        const r = rand() * (BALL_WALL_RADIUS - 0.5);
        b.x = Math.cos(a) * r;
        b.z = Math.sin(a) * r;
      } while (
        Math.abs(b.x) < GOAL_HALF_WIDTH + BALL_RADIUS + 0.1 &&
        b.z < GOAL_LINE_Z + BALL_RADIUS
      );
      // Half of the kicks aim at the goal mouth, the rest anywhere.
      const aim = rand() < 0.5;
      const tx = aim ? (rand() * 2 - 1) * (GOAL_HALF_WIDTH + 0.6) : 0;
      const dirX = aim ? tx - b.x : rand() * 2 - 1;
      const dirZ = aim ? GOAL_LINE_Z - b.z : rand() * 2 - 1;
      kickBall(b, dirX, dirZ, rand());
      players.length = 0;
      for (let i = 0, n = Math.floor(rand() * 4); i < n; i++)
        players.push({
          x: (rand() * 2 - 1) * 5,
          z: (rand() * 2 - 1) * 5,
          vx: 0,
          vz: 0,
          r: 0.38,
        });
      let scored = false;
      for (let i = 0; i < 30 * 30 && !scored; i++) {
        scored = (stepBall(b, players, players.length, dt) & 1) !== 0;
        if (![b.x, b.y, b.z, b.vx, b.vy, b.vz].every(Number.isFinite))
          bad.push(`run ${run}: non-finite`);
        if (Math.hypot(b.x, b.z) > BALL_WALL_RADIUS - BALL_RADIUS + 1e-6)
          bad.push(`run ${run}: outside the wall at step ${i}`);
        if (b.y < BALL_RADIUS - 1e-9)
          bad.push(`run ${run}: under the floor at step ${i}`);
        if (ballResting(b)) break;
      }
      if (scored) continue;
      if (!ballResting(b)) bad.push(`run ${run}: still moving after 30 s`);
      // At rest it lies on the floor: never on the roof, and never fully in
      // the goal without the goal event (on the line is legal: kick it out).
      if (b.y > BALL_RADIUS + 1e-6) bad.push(`run ${run}: resting in the air`);
      const inGoal =
        Math.abs(b.x) < GOAL_HALF_WIDTH &&
        b.z < GOAL_LINE_Z - BALL_RADIUS &&
        b.y < GOAL_HEIGHT;
      if (inGoal) bad.push(`run ${run}: stuck inside the goal`);
    }
    expect(bad).toEqual([]);
  });

  it('bodies walking through the goal mouth never leave the ball stuck inside (seeded fuzz, 1500 runs)', () => {
    const rand = rng(0xb0a1);
    const dt = 1 / 30;
    const bad: string[] = [];
    for (let run = 0; run < 1500; run++) {
      const b = createBall();
      b.x = (rand() * 2 - 1) * 2;
      b.z = GOAL_LINE_Z + rand() * 2;
      const players: BallPlayer[] = [];
      const targets: Array<[number, number]> = [];
      for (let i = 0, n = 1 + Math.floor(rand() * 3); i < n; i++) {
        players.push({
          x: (rand() * 2 - 1) * 3,
          z: GOAL_LINE_Z + 1 + rand() * 3,
          vx: 0,
          vz: 0,
          r: rand() < 0.3 ? 0.38 * 1.6 : 0.38,
        });
        // Anywhere across the mouth, often into the goal itself.
        targets.push([(rand() * 2 - 1) * 1.6, GOAL_LINE_Z - rand() * 0.7]);
      }
      let scored = false;
      for (let i = 0; i < 30 * 20 && !scored; i++) {
        const walking = i < 90;
        players.forEach((p, k) => {
          const [tx, tz] = targets[k];
          const d = Math.hypot(tx - p.x, tz - p.z);
          const speed = walking && d > 0.05 ? 2.2 + rand() * 1.8 : 0;
          p.vx = d > 0 ? ((tx - p.x) / d) * speed : 0;
          p.vz = d > 0 ? ((tz - p.z) / d) * speed : 0;
          // Server positions move in 10 Hz samples: every third step the body jumps 0.1 s on.
          if (walking && i % 3 === 0) {
            p.x += p.vx * 0.1;
            p.z += p.vz * 0.1;
          }
        });
        scored = (stepBall(b, players, players.length, dt) & 1) !== 0;
        if (Math.hypot(b.x, b.z) > BALL_WALL_RADIUS - BALL_RADIUS + 1e-6)
          bad.push(`run ${run}: outside the wall`);
        if (b.y < BALL_RADIUS - 1e-9) bad.push(`run ${run}: under the floor`);
        if (!walking && ballResting(b)) break;
      }
      if (scored) continue;
      const inGoal =
        Math.abs(b.x) < GOAL_HALF_WIDTH &&
        b.z < GOAL_LINE_Z - BALL_RADIUS &&
        b.y < GOAL_HEIGHT;
      if (inGoal) bad.push(`run ${run}: inside the goal without a goal`);
    }
    expect(bad).toEqual([]);
  });
});

describe('chip kick (decision B: a full-power chip can reach the crossbar)', () => {
  function peakRise(): number {
    const b = createBall();
    kickBall(b, 1, 0, 1);
    let top = 0;
    for (let i = 0; i < 60; i++) {
      stepBall(b, [], 0, 1 / 60);
      top = Math.max(top, b.y);
    }
    return top - BALL_RADIUS;
  }

  it('peaks about 0.88 m above rest at full power', () => {
    expect(peakRise()).toBeGreaterThan(0.86);
    expect(peakRise()).toBeLessThan(0.9);
  });

  it('hits the crossbar from mid range and still scores from long range', () => {
    const shot = (z0: number) => {
      const b = createBall();
      b.z = z0;
      kickBall(b, 0, -1, 1);
      let ev = 0;
      for (let i = 0; i < 120; i++) ev |= stepBall(b, [], 0, 1 / 60);
      return ev;
    };
    expect(shot(-2) & BALL_EVENT_BAR).toBeTruthy();
    expect(shot(2) & BALL_EVENT_GOAL).toBeTruthy();
  });
});

describe('optional solids', () => {
  it('bounces off a box and leaves the fixture path unchanged when none are passed', () => {
    const box = { minX: 1, maxX: 2, minZ: -0.5, maxZ: 0.5, maxY: 1.1 };
    const b = createBall();
    b.x = 0.5;
    kickBall(b, 1, 0, 0.4);
    let ev = 0;
    for (let i = 0; i < 90; i++) ev |= stepBall(b, [], 0, 1 / 60, undefined, [box]);
    expect(ev & BALL_EVENT_WALL).toBeTruthy();
    expect(b.x).toBeLessThan(box.minX);
  });
});
