import 'reflect-metadata';
import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { GamingSetupDto } from './gaming-setup.dto';
import { buildSetupLayout, validateSetupPlan, PlannedUnit } from './setup-plan';
import { selectGamingTariff } from './gaming-tariff';
const plan=():GamingSetupDto=>({venueId:'venue',requestKey:'key',floorCount:2,arrangement:'rows',ambience:'cafe',language:'ar',expectedRevision:0,reuseExisting:false,groups:[{assetKey:'ps5',count:6,hourlyRateMinor:12000,multiHourlyRateMinor:18000,floorIndex:0},{assetKey:'billiards',count:2,hourlyRateMinor:6000,floorIndex:1}],rooms:[{name:'VIP',floorIndex:1,occupancy:'independent',members:[{assetKey:'ps5',count:2}]}]});
describe('guided hall setup invariants',()=>{
 it('room stations count inside the total; seats do not select a paid mode',()=>{validateSetupPlan(plan());expect(selectGamingTariff({consoleType:'ps5',seats:8,multiHourlyRateMinor:18000},12000,'standard')).toBe(12000);expect(selectGamingTariff({consoleType:'ps5',seats:2,multiHourlyRateMinor:18000},12000,'multi')).toBe(18000);});
 it('rejects excess allocation, missing/repeated type, missing whole-room price and invalid floor',()=>{const variants=[()=>{const d=plan();d.rooms[0].members[0].count=7;return d;},()=>{const d=plan();d.rooms[0].members=[{assetKey:'ps4',count:1}];return d;},()=>{const d=plan();d.groups.push(d.groups[0]);return d;},()=>{const d=plan();d.rooms[0].occupancy='exclusive';return d;},()=>{const d=plan();d.groups[0].floorIndex=2;return d;}];for(const c of variants)expect(()=>validateSetupPlan(c())).toThrow();});
 it('rejects unsupported multi instead of silently charging standard',()=>{expect(()=>selectGamingTariff({consoleType:'ps5'},12000,'multi')).toThrow();expect(()=>selectGamingTariff({consoleType:'pc',multiHourlyRateMinor:18000},12000,'multi')).toThrow();});
 it('generates bounded floors with one placement per unit',()=>{let n=0;const units:PlannedUnit[]=Array.from({length:8},(_,i)=>({id:`u${i}`,assetKey:i<6?'ps5':'billiards',floorIndex:i<4?0:1,...(i===4||i===5?{roomIndex:0}:{})}));const doc=buildSetupLayout(plan(),units,()=>`id${++n}`);expect(doc.floors).toHaveLength(2);expect(doc.placements.filter(p=>p.unitId)).toHaveLength(8);expect(doc.placements.filter(p=>p.roomId)).toHaveLength(2);});
 it('whole-room parent is a selectable door with distinct child identity',()=>{const d=plan();d.rooms[0].occupancy='exclusive';d.rooms[0].hourlyRateMinor=25000;let n=0;const units:PlannedUnit[]=[{id:'a',assetKey:'ps5',floorIndex:1,roomIndex:0},{id:'b',assetKey:'ps5',floorIndex:1,roomIndex:0},{id:'parent',assetKey:'ps5',floorIndex:1,roomIndex:0,roomParent:true}];const doc=buildSetupLayout(d,units,()=>`id${++n}`);expect(doc.floors[1].rooms[0].bookableCourtId).toBe('parent');expect(doc.placements.find(p=>p.unitId==='parent')?.assetKey).toBe('door');});
 it('fits 100 stations in both arrangements',()=>{for(const arrangement of ['rows','walls'] as const){const d=plan();Object.assign(d,{floorCount:1,arrangement,groups:[{assetKey:'ps5',count:100,hourlyRateMinor:1,floorIndex:0}],rooms:[]});let n=0;const units:PlannedUnit[]=Array.from({length:100},(_,i)=>({id:`u${i}`,assetKey:'ps5',floorIndex:0}));expect(buildSetupLayout(d,units,()=>`id${++n}`).placements.filter(p=>p.unitId)).toHaveLength(100);}});
 it('nested DTO validation rejects fractions and negative money',async()=>{const d=plan();d.venueId='4c5920b9-9c0f-40bd-aacc-03e4cfe55f14';d.requestKey='1a2b91b8-5662-4f20-97c9-18cbd41bbf61';expect(await validate(plainToInstance(GamingSetupDto,d))).toHaveLength(0);expect((await validate(plainToInstance(GamingSetupDto,{...d,groups:[{...d.groups[0],count:1.5,hourlyRateMinor:-1}]}))).length).toBeGreaterThan(0);});
 it('validates floor allocations against the remaining open-hall total',()=>{const d=plan();d.groups[0].floorCounts=[2,2];expect(()=>validateSetupPlan(d)).not.toThrow();d.groups[0].floorCounts=[4,2];expect(()=>validateSetupPlan(d)).toThrow();});
});
